#!/bin/bash
# This script has Ubuntu 12.04 compatibility provisioning

set -e
set -x

source /etc/lsb-release
if [ $DISTRIB_CODENAME == 'precise' ]; then
  echo 'Provisioning Ubuntu 12.04 compatibility'
  export LANGUAGE=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  locale-gen en_US.UTF-8
  dpkg-reconfigure locales
  sudo apt-get install -y linux-headers-virtual linux-image-extra-virtual
fi

./provision-development